/** Langue « en » du score d'accroche : copie exacte des listes et motifs de hookscore.py. */
import type { LangueHook } from "./hookscore.ts";
import { fmt1 } from "./maths.ts";

export const HOOK_EN: LangueHook = {
  motRe: /[A-Za-z0-9$%'’-]+/g,
  nombreRe: /\$\s?\d[\d,]*(?:\.\d+)?|\b\d[\d,]*(?:\.\d+)?\s?(?:%|k\b|x\b|hrs?\b|hours?\b|mins?\b|minutes?\b|days?\b|weeks?\b|months?\b|years?\b)?/gi,
  propreRe: /(?<!^)\b[A-Z][a-z]{2,}\b/g,
  hashtagRe: /(?:^|\s)#\w+/,
  emojiRe: /[\u{1F300}-\u{1FAFF}☀-➿]/u,
  nombresParles: new Set(["zero", "two", "three", "four", "five", "six", "seven", "eight", "nine", "ten", "eleven", "twelve", "fifteen", "twenty", "thirty", "forty", "fifty", "sixty", "seventy", "eighty", "ninety", "hundred", "thousand", "million", "billion", "dozen", "half", "twice", "triple"]),
  motsArgent: new Set(["dollars", "dollar", "bucks", "grand", "percent", "cents", "millionaire", "billionaire", "revenue", "profit", "salary", "rent"]),
  enjeu: new Set([
    "stop", "never", "wrong", "mistake", "mistakes", "lost", "lose", "losing",
    "cost", "costs", "broke", "broken", "failed", "failure", "fail", "nobody",
    "no", "not", "don't", "dont", "doesn't", "didn't", "can't", "won't",
    "quit", "quitting", "fired", "deleted", "delete", "killed", "kills", "kill",
    "replaced", "replaces", "cut", "beat", "free", "paid", "charged", "hired",
    "saved", "first",
    "banned", "illegal", "worst", "hate", "hated", "wasted", "waste", "scam",
    "lie", "lied", "lying", "truth", "secret", "hidden", "stole", "stolen",
    "before", "until", "instead", "but", "except", "unless", "problem",
    "risk", "danger", "warning", "regret", "wish", "should", "shouldn't",
    "still", "already", "only", "without", "versus", "vs", "actually",
  ]),
  ouverturesFaibles: [
    "so", "ok", "okay", "hey", "hi", "hello", "guys", "yo", "alright",
    "welcome", "today", "basically", "honestly", "look", "listen", "um",
    "just", "let", "lets", "let's", "i wanted", "i want", "one of",
    "have you", "did you", "do you", "are you", "in this", "in today",
    "the thing", "a lot", "there is", "there are", "this is", "it is",
    "as a", "when it", "if you've", "you know",
  ],
  imperatifs: new Set(["stop", "steal", "copy", "delete", "try", "watch", "read", "save", "use", "build", "make", "write", "send", "take", "start", "quit", "never", "always", "don't", "dont", "do", "put", "run", "check"]),
  redhibitoires: [
    [/^\s*(?:stop scrolling|don'?t scroll)/i, "Opens with \"stop scrolling\". Asking for attention proves you have not earned it."],
    [/\b(?:in (?:this|today'?s) (?:video|reel)|i'?m going to show you|i'?ll show you how)\b/i, "Video preamble. Delete it and open on the payoff."],
    [/^\s*(?:hey |hi |what'?s up |welcome )/i, "Greeting. Nobody came to the feed to be greeted."],
    [/(?:^|\s)#\w+/, "Hashtag in the hook. Hashtags belong at the bottom of the caption, if anywhere."],
    [/[\u{1F300}-\u{1FAFF}☀-➿]/u, "Emoji in the hook. On-screen text at hook size has room for words or for an emoji, not both."],
  ],
  prixRe: /\$\s?\d/,
  toiRe: /\b(you|your|you're|youre|yourself)\b/,
  moiRe: /\b(i|my|me|we|our)\b/,
  separateurMilliers: /(?<=\d),(?=\d)/g,
  libelles: {
    prix: "a price",
    mots: (n, c, s) => `${n} words, ${c} chars, ~${fmt1(s)}s spoken (want 5-12 words)`,
    concrets: (n, t) => `${n} concrete marker(s)` + (t ? `: ${t}` : ""),
    rienConcret: " - no number, no name, nothing checkable",
    tension: (n, m) => `${n} tension marker(s)` + (m.length ? `: ${m.join(", ")}` : ""),
    rienEnjeu: " - nothing is at stake in this line",
    vide: "empty",
    aucunPayload: "no payload word anywhere in the line",
    payloadA: (i) => `payload at word ${i}`,
    payloadAvancer: (i) => `payload at word ${i}, could move forward`,
    payloadTard: (i) => `payload at word ${i}, too late`,
    ouvertureFaible: (o) => `; weak opener "${o}"`,
    parleAuSpectateur: "speaks to the viewer",
    imperatif: (w) => `imperative opener ("${w}")`,
    premierePersonne: "first person, no viewer named",
    troisiemePersonne: "third person, nobody in the room",
  },
};
